// SPDX-FileCopyrightText: © 2020 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= Node Docker Image Slimming
Sebastian Davids <sdavids@gmx.de>
// Metadata:
:description: Techniques for creating a smaller Node.js Docker image.
// Settings:
:sectnums:
:sectanchors:
:sectlinks:
:toc: macro
:toclevels: 3
:toc-placement!:
:hide-uri-scheme:
:source-highlighter: rouge
:rouge-style: github
:experimental:

ifdef::env-browser[:outfilesuffix: .adoc]

ifdef::env-github[]
:outfilesuffix: .adoc
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:warning-caption: :warning:
:badges:
endif::[]

toc::[]

[WARNING]
====
This branch will be force-pushed to in order to keep it up-to date with the main branch and remain a single commit.
====

Further documentation can be found on the main branch: https://github.com/sdavids/sdavids-node-docker-image-slimming/blob/main/README.adoc[README.adoc]

== Branch Content

This branch utilizes:

* the `alpine` variant of the https://hub.docker.com/_/node/[offical NodeJS Docker image] for building the image
* the https://hub.docker.com/_/alpine/[official Alpine Docker image] for serving the example REST API
+
[NOTE]
====
Depending on your project setup you might have to install more packages via `apk add --no-cache`.

The dependencies of `docker run --rm alpine apk add nodejs` might be a starting point.functions might help fine-tuning your `.dockerignore` file.
====
* use a https://docs.docker.com/reference/dockerfile/#dockerignore-file[.dockerignore file] and specific `COPY` commands
+
[NOTE]
====
The https://github.com/sdavids/sdavids-shell-misc?tab=readme-ov-file#212-ls_extensions[ls_extensions] and https://github.com/sdavids/sdavids-shell-misc?tab=readme-ov-file#ls_extensions_git[ls_extensions_git] functions might help fine-tuning your `.dockerignore` file.
====
* use `npm ci --omit dev --omit optional --omit peer` instead of `npm i`
+
[NOTE]
====
Depending on your project setup you might not be able to omit the https://nodejs.org/en/blog/npm/peer-dependencies[peer dependencies].
====
* use `npm cache clean --force`
* use the https://www.npmjs.com/package/clean-modules[clean-modules] npm package to clean up the `node_modules` directory
+
[NOTE]
====
`clean-modules` will have more impact once there are more dependencies.
====
* use a multi-stage build
* use https://upx.github.io[UPX] to compress the `node` binary
* harden the final `alpine` image
+
[NOTE]
====
Hardening does not only decrease the image size but also makes it significantly more secure.
====

=== Result

[source,shell]
----
$ SOURCE_DATE_EPOCH=1 GITHUB_SHA="N/A" scripts/docker-build.sh -n
...
$ docker images --filter="label=de.sdavids.docker.group=sdavids-node-docker-image-slimming" --format "{{.Repository}}\t{{.Tag}}\t{{.Size}}"
de.sdavids/sdavids-node-docker-image-slimming   latest  114MB
de.sdavids/sdavids-node-docker-image-slimming   local   114MB
$ docker run --rm de.sdavids/sdavids-node-docker-image-slimming:local du -hs /node
22.4M   /node
$ docker run --rm de.sdavids/sdavids-node-docker-image-slimming:local du -hs /node/node_modules
22.4M   /node/node_modules
$ docker run --rm de.sdavids/sdavids-node-docker-image-slimming:local stat -c "%s" /node/server.mjs
2139
$ docker run --rm de.sdavids/sdavids-node-docker-image-slimming:local ls -A /node
healthcheck.mjs
node_modules
server.mjs
tmp
$ docker image history --format "table {{.Size}}\t{{.CreatedBy}}" de.sdavids/sdavids-node-docker-image-slimming:local
SIZE      CREATED BY
0B        LABEL org.opencontainers.image.revision=N/A …
0B        HEALTHCHECK &{["CMD-SHELL" "node --no-warnin…
0B        CMD ["node" "server.mjs"]
0B        EXPOSE map[3000/tcp:{}]
0B        USER node
0B        ENV APP_DIR=/node
0B        ENV KEY_PATH=/run/secrets/key.pem
0B        ENV CERT_PATH=/run/secrets/cert.pem
0B        ENV PORT=3000
0B        ENV NODE_ENV=production
16.4kB    COPY --chown=node:node /opt/app ./ # buildkit
23.5MB    COPY --chown=node:node /opt/app/node_modules…
35.7MB    COPY --chown=node:node /usr/local/bin/node /…
2.86MB    COPY --chown=node:node /usr/lib/libgcc_s.so.…
4.1kB     WORKDIR /node
0B        ARG key_path=/run/secrets/key.pem
0B        ARG cert_path=/run/secrets/cert.pem
0B        ARG port=3000
0B        ARG created_at
0B        ARG git_commit
0B        ARG app_dir=/node
0B        ARG user=node
0B        ENV TMPDIR=/node/tmp
1.43MB    RUN |3 uid=1001 user=node app_dir=/node /bin…
0B        SHELL [/bin/ash -eo pipefail -c]
0B        ARG app_dir=/node
0B        ARG user=node
0B        ARG uid=1001
0B        /bin/sh -c #(nop)  CMD ["/bin/sh"]
8.07MB    /bin/sh -c #(nop) ADD file:37a76ec18f9887751…
$ printf 'Layer Count: %s' "$(docker history de.sdavids/sdavids-node-docker-image-slimming:local | tail -n +2 | wc -l | tr -d ' ')"
Layer Count: 30
----

=== More Information

* https://docs.docker.com/reference/dockerfile/#dockerignore-file[.dockerignore file]
* https://docs.docker.com/reference/dockerfile/#copy[Dockerfile - COPY]
* https://hub.docker.com/_/node[node:<version>-alpine]
* https://docs.npmjs.com/cli/v10/commands/npm-ci[npm-ci]
* https://docs.npmjs.com/cli/v10/commands/npm-ci#omit[npm-ci --omit]
* https://docs.npmjs.com/cli/v10/commands/npm-cache[npm-cache]
* https://www.npmjs.com/package/clean-modules[clean-modules]
* https://docs.docker.com/build/building/multi-stage/[Multi-stage builds]
* https://hub.docker.com/_/alpine/[Official Alpine Docker Image]
* https://upx.github.io[UPX]
* https://github.com/ironpeakservices/iron-alpine[iron-alpine]
