// SPDX-FileCopyrightText: © 2020 Sebastian Davids <sdavids@gmx.de>
// SPDX-License-Identifier: Apache-2.0
= Node Docker Image Slimming
Sebastian Davids <sdavids@gmx.de>
// Metadata:
:description: Techniques for creating a smaller Node.js Docker image.
// Settings:
:sectnums:
:sectanchors:
:sectlinks:
:toc: macro
:toclevels: 3
:toc-placement!:
:hide-uri-scheme:
:source-highlighter: rouge
:rouge-style: github
:experimental:

ifdef::env-browser[:outfilesuffix: .adoc]

ifdef::env-github[]
:outfilesuffix: .adoc
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:warning-caption: :warning:
:badges:
endif::[]

toc::[]

[WARNING]
====
This branch will be force-pushed to in order to keep it up-to date with the main branch and remain a single commit.
====

Further documentation can be found on the main branch: https://github.com/sdavids/sdavids-node-docker-image-slimming/blob/main/README.adoc[README.adoc]

== Branch Content

This branch utilizes:

* the `alpine` variant of the https://hub.docker.com/_/node/[offical NodeJS Docker image] for building the image
* the `alpine` variant of the https://hub.docker.com/_/node/[offical NodeJS Docker image] for serving the example REST API
* use a https://docs.docker.com/reference/dockerfile/#dockerignore-file[.dockerignore file] and specific `COPY` commands
+
[NOTE]
====
The https://github.com/sdavids/sdavids-shell-misc?tab=readme-ov-file#212-ls_extensions[ls_extensions] and https://github.com/sdavids/sdavids-shell-misc?tab=readme-ov-file#ls_extensions_git[ls_extensions_git] functions might help fine-tuning your `.dockerignore` file.
====
* use `npm ci --omit dev --omit optional --omit peer` instead of `npm i`
+
[NOTE]
====
Depending on your project setup you might not be able to omit the https://nodejs.org/en/blog/npm/peer-dependencies[peer dependencies].
====
* use `npm cache clean --force`

=== Result

[source,shell]
----
$ SOURCE_DATE_EPOCH=1 GITHUB_SHA="N/A" scripts/docker-build.sh -n
...
$ docker images --filter="label=de.sdavids.docker.group=sdavids-node-docker-image-slimming" --format "{{.Repository}}\t{{.Tag}}\t{{.Size}}"
de.sdavids/sdavids-node-docker-image-slimming   latest  233MB
de.sdavids/sdavids-node-docker-image-slimming   local   233MB
$ docker run --rm de.sdavids/sdavids-node-docker-image-slimming:local du -hs /node
38.4M   /node
$ docker run --rm de.sdavids/sdavids-node-docker-image-slimming:local du -hs /node/node_modules
38.3M   /node/node_modules
$ docker run --rm de.sdavids/sdavids-node-docker-image-slimming:local stat -c "%s" /node/server.mjs
2139
$ docker run --rm de.sdavids/sdavids-node-docker-image-slimming:local ls -A /node
healthcheck.mjs
node_modules
package-lock.json
package.json
scripts
server.mjs
$ docker image history --format "table {{.Size}}\t{{.CreatedBy}}" de.sdavids/sdavids-node-docker-image-slimming:local
SIZE      CREATED BY
0B        LABEL org.opencontainers.image.revision=N/A …
0B        HEALTHCHECK &{["CMD-SHELL" "node --no-warnin…
0B        CMD ["node" "server.mjs"]
0B        EXPOSE map[3000/tcp:{}]
0B        USER node
0B        ENV APP_DIR=/node
0B        ENV KEY_PATH=/run/secrets/key.pem
0B        ENV CERT_PATH=/run/secrets/cert.pem
0B        ENV PORT=3000
0B        ENV NODE_ENV=production
16.4kB    COPY --chown=node:node src/js ./ # buildkit
40.5MB    RUN |7 user=node app_dir=/node git_commit=N/…
168kB     COPY package.json package-lock.json ./ # bui…
20.5kB    COPY scripts/preinstall.sh scripts/prepare.s…
8.19kB    WORKDIR /node
0B        ARG key_path=/run/secrets/key.pem
0B        ARG cert_path=/run/secrets/cert.pem
0B        ARG port=3000
0B        ARG created_at
0B        ARG git_commit
0B        ARG app_dir=/node
0B        ARG user=node
0B        /bin/sh -c #(nop)  CMD ["node"]
0B        /bin/sh -c #(nop)  ENTRYPOINT ["docker-entry…
20.5kB    /bin/sh -c #(nop) COPY file:4d192565a7220e13…
5.71MB    /bin/sh -c apk add --no-cache --virtual .bui…
0B        /bin/sh -c #(nop)  ENV YARN_VERSION=1.22.19
128MB     /bin/sh -c addgroup -g 1000 node     && addu…
0B        /bin/sh -c #(nop)  ENV NODE_VERSION=20.13.1
0B        /bin/sh -c #(nop)  CMD ["/bin/sh"]
8.07MB    /bin/sh -c #(nop) ADD file:37a76ec18f9887751…
$ printf 'Layer Count: %s' "$(docker history de.sdavids/sdavids-node-docker-image-slimming:local | tail -n +2 | wc -l | tr -d ' ')"
Layer Count: 31
----

=== More Information

* https://docs.docker.com/reference/dockerfile/#dockerignore-file[.dockerignore file]
* https://docs.docker.com/reference/dockerfile/#copy[Dockerfile - COPY]
* https://hub.docker.com/_/node[node:<version>-alpine]
* https://docs.npmjs.com/cli/v10/commands/npm-ci[npm-ci]
* https://docs.npmjs.com/cli/v10/commands/npm-ci#omit[npm-ci --omit]
* https://docs.npmjs.com/cli/v10/commands/npm-cache[npm-cache]
