#!/usr/bin/env sh

# shellcheck shell=sh

# SPDX-FileCopyrightText: © 2024 Sebastian Davids <sdavids@gmx.de>
# SPDX-License-Identifier: Apache-2.0

set -eu

npx --yes --quiet commitlint --strict --edit "${1}" >&2
