---
# https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md

openapi: 3.1.0

info:
  title: sdavids-node-docker-image-slimming REST API
  version: 0.0.1
  description: A simple endpoint in NodeJS with Express.
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: Sebastian Davids
    email: sdavids@gmx.de

tags:
  - name: API
  - name: Management

components:
  schemas:
    User:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
          format: email
    Liveness:
      type: object
      properties:
        status:
          type: string
          enum:
            - UP
            - DOWN
  examples:
    random-user-ok:
      value:
        userId: d13e3ec3-cb8f-4fb1-8cf5-55175e5735f7
        username: Cameron_Howe
        email: c.howe@mutiny.com
    liveness-ok:
      value:
        status: UP

paths:
  /:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                ok:
                  $ref: '#/components/examples/random-user-ok'
      summary: Random User
      description: Returns a random user.
      operationId: getRandomUser
      tags:
        - API
  /-/health/liveness:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Liveness'
              examples:
                ok:
                  $ref: '#/components/examples/liveness-ok'
      summary: Liveness Probe
      description: Liveness Probe
      operationId: getLivenessProbe
      tags:
        - Management

servers:
  - url: http://localhost:3000
    description: local
  - url: https://localhost:3000
    description: local secure
